name: detonados
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.2.1+2
  flutter_launcher_icons: "^0.7.3"
  material_design_icons_flutter: 3.4.4795

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "image/pokeball.png"

flutter:
  uses-material-design: true

  assets:
   - image/pokeball.png